package ImageHoster.repository;

import ImageHoster.model.Comment;
import org.springframework.stereotype.Repository;

import javax.persistence.*;
import java.util.List;

//Repository for all Comment Related Methods
@Repository
public class CommentRepository {
    @PersistenceUnit(unitName = "imageHoster")
    private EntityManagerFactory emf;

    //Using the ImageId we are able to fetch all comments having that image id
    public List<Comment> getAllComments(Integer imageId) {
        EntityManager em = emf.createEntityManager();
        TypedQuery<Comment> query = em.createQuery("SELECT c FROM Comment c WHERE c.image.id = :imageId", Comment.class);
        query.setParameter("imageId",imageId);
        List<Comment> resultList = query.getResultList();

        return resultList;
    }

    //With the comment entity generated by a user now it needs to be committed to the database
    //Using em.persist() the value of the entity is entered to the corresponding table in backend
    public void addComment(Comment newComment){
        EntityManager em = emf.createEntityManager();
        EntityTransaction transaction = em.getTransaction();

        try {
            transaction.begin();
            //persist() method changes the state of the model object from transient state to persistence state
            em.persist(newComment);
            transaction.commit();
        } catch (Exception e) {
            transaction.rollback();
        }
    }
}
